const productSpecificationDummy = {
    Manufacturer: 'Apple',
    Warranty: '1 year external service',
    'Product group': 'Apple iPad',
    Condition: 'new',
    'Screen size': '8.3 inches',
    'Touch technology': 'capacitive (10-point)',
    'Display type': 'IPS Retina',
    Version: 'Wi-Fi',
    'Native resolution': '2266 x 1488 pixels',
    Brightness: '500 nits',
    Technology: 'stylus support, anti-reflective coating, fingerprint-resistant coating',
    'Processor family': 'Apple',
    'Processor model': 'Apple A17 Pro',
    'SSD capacity': '128 GB',
    Ports: '1 x USB Type-C, docking connector',
    Communication: 'Bluetooth 5.2, Wi-Fi 6E',
    'Built-in microphone': 'yes (2 x microphone)',
    'Built-in speakers': '4 speakers',
    'Rear camera': '12 MP (f1.8)',
    'Front camera': '12 MP (f2.4)',
    Zoom: '5x (digital)',
    'Video recording': '1920 x 1080 (FHD), 3840 x 2160 (4K), 720p',
    'Battery type': 'lithium-polymer (LiPoly)',
    Platform: 'Apple iOS',
    'Operating system': 'Apple iOS 18',
    'Sensors and components':
        'accelerometer, barometer, light sensor, fingerprint reader, digital compass, magnetometer, gyroscope',
    Color: 'space gray',
    Width: '135 mm',
    Height: '195 mm',
    Thickness: '6 mm',
    Weight: '293 g',
    'Body material': 'aluminum',
    Accessories: 'USB cable, charger',
    Series: 'Apple iPad',
    Model: 'Apple iPad Mini (7th gen | 2024)',
}

export default productSpecificationDummy
